config/routes.rb
Cinecinetique::Application.routes.draw do

  resources :paypal_notifications

  resources :budget_lines

  resources :budgets

  resources :proposals

  resources :subscriptions do
    collection do
      get :complete_checkout
      post :payment_notifications
    end
  end

  resources :subscriptions

  devise_for :users, :controllers => { :registrations => 'registrations' }
  
  get '/portfolio', :to => redirect('/portfolio/index.html')

  resources :plans

  controller :scenes do
    post 'sort' => :sort
  end

  controller :static do
    get 'pricing' => :pricing
    get 'terms' => :terms
    get 'product' => :product
  end

  resources :scenes

  resources :projects

  resources :users do
    collection do
      post :invite
    end
  end

  resources :users

  resources :documents do
    get :share
  end

  resources :documents do
    collection do
      get 'heartbeat'
    end
  end

  
  resources :documents

  resources :pdfs, :controller => 'documents'
  resources :mswords, :controller => 'documents'
  resources :msexcels, :controller => 'documents'
  resources :images, :controller => 'documents'
  resources :videos, :controller => 'documents'
  resources :audios, :controller => 'documents'

  resources :workers

    get 'home' => "static#index"
    root :to => "static#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :workers, dependent: :destroy
  accepts_nested_attributes_for :workers, :allow_destroy => true

  after_create :setup_initial_role


  def projects
  	workers.map { |w| w.project }
  end

  def projects_created
    Project.where("created_by = #{id}")
  end

  def managed_users
    projects_teams = []

    projects_created.each do |project| 
      project.team.each { |member| projects_teams << member}
    end
    projects_teams.uniq
  end

  def position(project_id)
    if project_id
      Worker.where("user_id = #{id} and project_id = #{project_id}").first
    end
  end

  def can_admin?
  	is_admin
  end

  def setup_initial_role
    self.add_role :member
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  #skip_before_action :authorize, only: [:new, :create]
  skip_before_filter :authenticate_user!, :only => [:new, :create]

  # GET /users
  # GET /users.json
  def index
    if session[:current_project] && Project.ids.include?(session[:current_project])
      @workers = Worker.where("project_id = #{session[:current_project]}")
      @users = @workers.map { |w| w.user}
    else
      @workers = []
      @users = []
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
    @worker = Worker.new
    @user.workers.build
  end

  # GET /users/1/edit
  def edit
    @user.workers.build
  end

  # POST /users/invite/[:user_email,:project_id]
  def invite
    user_name =  params[:name] if params[:name] =~ /[0-9a-zA-Z\s]+/
    user_email = params[:email] if params[:email] =~ /[0-9a-zA-Z@\s_-]+/
    project = Project.find(params[:project_id])
    respond_to do |format|
      if user_name && user_email && project && send_invite(project, user_name, user_email)
        format.html { redirect_to users_url, notice: "An invite was successfully sent to #{user_email} " }
      else
        format.html { 
          redirect_to users_url, notice: "Could not send invite to #{user_name}, #{user_email}"
        }
      end
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: "User #{@user.email} was successfully created." }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_url, notice: "User #{@user.email} was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :workers_attributes => [:id, :role, :department, :project_id])
    end

    def send_invite(project, user_name, user_email)
      begin
        InvitationMailer.email_invitation(project, user_name, user_email, current_user).deliver
      rescue Exception => ex
        Rails.logger.error("Error when sending invitation email to #{user_email}: #{ex.to_s}")
        false
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_find_form.html.erb
<%= form_tag('/users/invite') do -%>


  <fieldset>
    <legend>Or invite a user by email</legend>
    
    <div class="field">
      <%= label_tag :name %><br>
      <%= text_field_tag :name %>
    </div>

    <div class="field">
      <%= label_tag :email %><br>
      <%= text_field_tag :email %>
    </div>


    <%= hidden_field_tag :project_id, "#{session[:current_project]}" %>
  </fieldset>

  <div class="actions">
    <%= submit_tag 'Send invite' %>
  </div>

  <% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <legend>Or create a new user</legend>
    
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :password %><br>
      <%= f.password_field :password %>
    </div>
    <div>
      <%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation %>
    </div>
    <% if @user.workers.count > 0 %>

      <%= f.fields_for :workers, @user.workers.where("project_id = #{session[:current_project]}") do |builder| %>
       
        <div class="field">
          <%= builder.label :role %><br />
          <%= builder.text_field :role %>
        </div>

        <div class="field">
          <%= builder.label :department %><br />
          <%= builder.text_field :department %>
        </div>

        <%= builder.hidden_field :project_id, :value => "#{session[:current_project]}" %>

      <% end -%>
    <% else %>

      <%= f.fields_for :workers do |builder| %>
       
        <div class="field">
          <%= builder.label :role %><br />
          <%= builder.text_field :role %>
        </div>

        <div class="field">
          <%= builder.label :department %><br />
          <%= builder.text_field :department %>
        </div>

        <%= builder.hidden_field :project_id, :value => "#{session[:current_project]}" %>

      <% end -%>
    <% end %>



    <div class="actions">
      <%= f.submit %>
    </div>

  </fieldset>
<% end %>

app/views/users/_workerform.html.erb
<%= form_for(@worker) do |f| %>

<fieldset>
    <legend>Add a user you've worked with to the project</legend>
     <%= f.select :user_id, User.find(current_user.id).managed_users.map { |u| [u.name,u.id]},
prompt: 'Select a user', include_blank: true %>
        <div class="field">
          <%= f.label :role %><br />
          <%= f.text_field :role %>
        </div>

        <div class="field">
          <%= f.label :department %><br />
          <%= f.text_field :department %>
        </div>

        <%= f.hidden_field :project_id, :value => "#{session[:current_project]}" %>
</fieldset>

   <div class="actions">
      <%= f.submit "Add to project" %>
    </div>


<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Role</th>
      <th>Department</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.workers.where("project_id = #{session[:current_project]}").first.role %></td>
        <td><%= user.workers.where("project_id = #{session[:current_project]}").first.department %></td>
        <td><%= link_to 'Show', user, :class => "btn btn-mini btn-default"%></td>
        <td><%= link_to 'Edit Role', edit_worker_path(Worker.find_by_user_id_and_project_id(user.id,session[:current_project])),  :class => "btn btn-mini btn-primary" %></td>
        <td><%= link_to 'Remove', worker_path(user.position(session[:current_project])), method: :delete, data: { confirm: "Are you sure you want to remove #{user.name} from the project?" }, :class => "btn btn-mini btn-warning"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Find or invite a new user for the project ', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'workerform' %>

<%= render 'find_form' %>


<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<h3>User Info</h3>
<table class="table">
	<thead>
    <tr>
      <th>Name</th>
      <th>Role</th>
      <th>Department</th>
    </tr>
  </thead>
  <tbody>
  	<% if session[:current_project] and Project.ids.include?(session[:current_project]) %>
	  <tr><td> <%= mail_to @user.email, @user.name %></td><td><%= @user.position(session[:current_project]).role %></td><td><%= @user.position(session[:current_project]).department %></td></tr>
	<% end %>
  </tbody>
</table>

<h3>Tasks List</h3>
<%= render 'layouts/tasks' %> 

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>