config/routes.rb
Cinecinetique::Application.routes.draw do

  resources :paypal_notifications

  resources :budget_lines

  resources :budgets

  resources :proposals

  resources :subscriptions do
    collection do
      get :complete_checkout
      post :payment_notifications
    end
  end

  resources :subscriptions

  devise_for :users, :controllers => { :registrations => 'registrations' }
  
  get '/portfolio', :to => redirect('/portfolio/index.html')

  resources :plans

  controller :scenes do
    post 'sort' => :sort
  end

  controller :static do
    get 'pricing' => :pricing
    get 'terms' => :terms
    get 'product' => :product
  end

  resources :scenes

  resources :projects

  resources :users do
    collection do
      post :invite
    end
  end

  resources :users

  resources :documents do
    get :share
  end

  resources :documents do
    collection do
      get 'heartbeat'
    end
  end

  
  resources :documents

  resources :pdfs, :controller => 'documents'
  resources :mswords, :controller => 'documents'
  resources :msexcels, :controller => 'documents'
  resources :images, :controller => 'documents'
  resources :videos, :controller => 'documents'
  resources :audios, :controller => 'documents'

  resources :workers

    get 'home' => "static#index"
    root :to => "static#index"

end

app/models/document.rb
require 'firebase'

class Document < ActiveRecord::Base

  HOST_TYPES = [ "vimeo", "youtube" ]
      belongs_to :project
      validates :name, :presence => true
      validates :data_ref, :presence => true, unless: Proc.new { |d| d.data_host.blank? }
      validates :data_host, :presence => true, unless: Proc.new { |d| d.data_ref.blank? }
      validates :data_host, inclusion: { in: HOST_TYPES, message: "%{value} is not a valid host service" },
                 unless: Proc.new { |d| d.data_host.blank? }
    	has_attached_file :data,
    			              :default_url => "/images/:style/missing.png",
                        :bucket => proc { |attachment| attachment.instance.project.bucket_name }
      validates_attachment :data
      before_post_process :media?

	def video?
      [ 'application/x-mp4',
            'video/mpeg',
            'video/quicktime',
            'video/x-la-asf',
            'video/x-ms-asf',
            'video/x-msvideo',
            'video/x-sgi-movie',
            'video/x-flv',
            'flv-application/octet-stream',
            'video/3gpp',
            'video/3gpp2',
            'video/3gpp-tt',
            'video/BMPEG',
            'video/BT656',
            'video/CelB',
            'video/DV',
            'video/H261',
            'video/H263',
            'video/H263-1998',
            'video/H263-2000',
            'video/H264',
            'video/JPEG',
            'video/MJ2',
            'video/MP1S',
            'video/MP2P',
            'video/MP2T',
            'video/mp4',
            'video/MP4V-ES',
            'video/MPV',
            'video/mpeg4',
            'video/mpeg4-generic',
            'video/nv',
            'video/parityfec',
            'video/pointer',
            'video/raw',
            'video/rtx' ].include?(data.content_type)
  end

  def image?
      !(data_content_type =~ /^image.*/).nil?
  end 

  def audio?
      !(data_content_type =~ /^audio.*/).nil?
  end 

  def pdf?
      data_content_type == 'application/pdf'
  end

  def media?
      video? || image? || audio? || pdf?
  end

  def xls?
      data_content_type == 'application/vnd.ms-excel'
  end

  def xlsx?
      data_content_type == 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
  end

  def doc?
      data_content_type == 'application/msword'
  end

  def docx?
      data_content_type == 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
  end

  def office?
    doc? || docx? || xls? || xlsx?
  end

  def to_partial_path
    'documents/document'
  end


end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
    @project_id = params[:project_id]
  end

  # GET /documents/heartbeat
  def heartbeat
    respond_to :js
  end

  # GET /documents/share/1
  def share
    document = Document.find(params[:document_id])
    redirect_to signed_url_for('original',document)
  end
  
  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    if document_params[:data] == nil
      logger.warn "**** USING DOCUMENT! ****"
      @document = Document.new(document_params)
    elsif Pdf.content_types.include?(document_params[:data].content_type)
      @document = Pdf.new(document_params)
    elsif Msword.content_types.include?(document_params[:data].content_type)
      @document = Msword.new(document_params)
    elsif Msexcel.content_types.include?(document_params[:data].content_type)
      @document = Msexcel.new(document_params)
    elsif Image.content_types.include?(document_params[:data].content_type)
      @document = Image.new(document_params)
    elsif Video.content_types.include?(document_params[:data].content_type)
      @document = Video.new(document_params)
    elsif Audio.content_types.include?(document_params[:data].content_type)
      @document = Audio.new(document_params)
    else
      logger.warn "**** USING DOCUMENT! ****"
      @document = Document.new(document_params)
    end

    @document.created_by = current_user.id
    @document.changed_by = current_user.id

    document_cycle = DocumentCycle.new(@document)

    respond_to do |format|
      if document_cycle.create
        format.html { redirect_to document_url(@document) }
        format.json { render action: 'show', status: :created, location: @document }
      else
        format.html { render action: 'new' }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update

    @document.changed_by = current_user.id
    document_cycle = DocumentCycle.new(@document)
    respond_to do |format|
      if document_cycle.update(document_params(@document.class.to_s))
        format.html { redirect_to document_url(@document) }
        format.json { head :no_content }
      else
        format.html { render action: 'edit'}
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy

    logger.info "document deleted by #{current_user.id}"
    project = @document.project
    @document.destroy
    respond_to do |format|
      format.html { redirect_to project }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params(kind = nil)
      if kind
        params.require(kind.downcase.to_sym).permit(:name, :project_id, :data, :scene_number,:data_ref, :data_host, :location, :page, :changed_by)
      else
        params.require(:document).permit(:name, :project_id, :data, :scene_number,:data_ref, :data_host, :location, :page, :changed_by)
      end
    end

    def signed_url_for(style, document)
      if Cinecinetique::STORAGE == :s3
        s3 = AWS::S3.new()
        url = s3.buckets[document.project.bucket_name].objects[document.data.path(style)[1..-1]].url_for(:read)
        url.to_s
      else
        @document.data.url(style)
      end
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
	require 'cgi'
	
	def signed_url_for(style, document)
		if Cinecinetique::STORAGE == :s3
			s3 = AWS::S3.new()
			url = s3.buckets[document.project.bucket_name].objects[document.data.path(style)[1..-1]].url_for(:read)
			url.to_s
		else
			document.data.url(style)
		end
	end

	def google_viewer_url(url)
		gv_url = "http://docs.google.com/viewer?url=#{CGI.escape(url)}&embedded=true"
	end


end

app/views/documents/_document.html.erb
      <tr id="<%= "document_#{document.name.parameterize}" %>">
      	<td><%= document.scene_number %></td>
        <td id="<%= document.id %>" draggable>
        <% if document.image? || document.pdf? %>
          <%= image_tag signed_url_for(:thumb, document), :id => document.id, :class => "img-thumbnail img-responsive" %>  
        <% elsif document.xls? || document.xlsx? %>
          <%= image_tag "/images/excel.png", :id => document.id, :class => "img-thumbnail img-responsive" %>
        <% elsif document.doc? || document.docx? %>
          <%= image_tag "/images/word.png", :id => document.id, :class => "img-thumbnail img-responsive" %>
        <% elsif document.audio? %>
          <%= image_tag "/images/audio.png", :id => document.id, :class => "img-thumbnail img-responsive" %>
        <% elsif document.data_host == 'youtube' %>
          <%= image_tag "http://img.youtube.com/vi/#{document.data_ref}/2.jpg", :id => document.id, :class => "img-thumbnail img-responsive" %>
        <% elsif document.data_host == 'vimeo' %>
        <%= image_tag "#{vimeo_thumbnail(document)}", :size => "120x90", :id => document.id, :class => "img-thumbnail img-responsive" %>
        <% else %>
          <%= image_tag "/images/file.png", :id => document.id, :class => "img-thumbnail img-responsive" %>
        <% end %>
        </td>

        <td id="document-name-<%= document.id %>"><%= document.name %></td>
        <!-- <td><%= document.data_content_type %></td> -->
        <!-- <td><%= document.project.name %></td> -->
        <td data-no-turbolink><%= link_to 'Show', document, :class => "btn btn-mini btn-default" %></td>
        <td><%= link_to 'Edit', edit_document_path(document),  :class => "btn btn-mini btn-primary" %></td>
        <td><%= link_to 'Delete', document, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-mini btn-danger" %></td>
      </tr>

app/views/documents/_form.html.erb
<%= form_for(@document,:html => {:multipart => true}) do |f| %>
  <% if @document.errors.any? %>
    <div class="alert alert-error" id="error_explanation">
      <%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:

      <ul>
      <% @document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<fieldset>
  <div class="field">
    <%= f.label :name %>
    <div class="input-prepend"><span class="add-on"><i class="icon-file"></i></span><%= f.text_field :name %></div>
  </div>

  <div class="field">
    <%= f.label "Scene number" %>
    <div class="input-prepend"><span class="add-on"><i class="icon-facetime-video"></i></span><%= f.text_field :scene_number %></div>
  </div>

  <div class="field">
    <%= f.label :location %>
    <div class="input-prepend"><span class="add-on"><i class="icon-globe"></i></span><%= f.text_field :location %></div>
  </div>

    <div class="field">
    <%= f.label :page %>
    <div class="input-prepend"><span class="add-on"><i class="icon-book"></i></span><%= f.text_field :page %></div>
  </div>
  </fieldset>

 <!--  <div class="" id="DataSelectionModal">
          <div class="modal-body"> -->
            <div class="well">
                <ul class="nav nav-tabs">
                  <li class="active"><a href="#upload" data-toggle="tab">Upload from Computer</a></li>
                  <li><a href="#hosted" data-toggle="tab">Add external video link</a></li>
                </ul>
                <div id="myTabContent" class="tab-content">
                
                        <div class="tab-pane active in" id="upload">

                            <fieldset>
                            <div class="field">
                              <%= f.label :data %>
                              <%= f.file_field :data %>
                              <span class="help-inline"><span class="label label-info">Info</span> Accepted formats are Word, Excel, JPG, GIF, PNG, PDF, MOV, MP4, Wav, MP3</span></br>
                              <span class="help-inline"><span class="label label-warning">Warning</span> Please be aware that there is currently an issue (being worked on) whereby the page can become irresponsive when uploading audio or video files. However, you can still know when the upload is finished as a new notification will still trigger in the top navigation bar upon completion. </span>
                            </div>
                            </fieldset>
            
                        </div>

                        <div class="tab-pane fade" id="hosted">
                              <fieldset>

                              <div class="field">
                                <%= f.label :data_host %><br>
                                <%= f.select :data_host, Video::HOST_TYPES,
                            prompt: 'Select a video hosting', include_blank: true %>
                              </div>
                              </span>
                              <div class="field">
                                <%= f.label :data_ref %><br>
                                <%= f.text_field :data_ref %>
                              </div>
                              <span class="help-block">e.g: http://www.youtube.com/watch?v=[<b>Data ref</b>]</span>
                              <span class="help-block">or http://vimeo.com/[<b>Data ref</b>]
                            </fieldset>
                        </div>
                </div>
            </div>


  <iframe id="feedback" name="feedback" title="empty" style="display:none" data-url="<%= heartbeat_documents_path %>" tabindex="-1" width="0" height="0" seamless></iframe>
  <div class="actions">
    <%= f.hidden_field :project_id, :value => "#{session[:current_project]}" %>
    <%= f.submit %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing document</h1>

<%= render 'form' %>


<%= link_to 'Show', @document %> |
<%= link_to 'Back', project_path(@document.project) %>

app/views/documents/heartbeat.js.erb
KeepAlive.poll();

app/views/documents/index.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<% if session[:user_id] %>
<p id="session"> Logged In (<%= link_to 'Logout', logout_path, method: :delete %>)</p>
<% end %>

<h1>Listing documents</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Kind</th>
      <th>Project</th>
      <th>Thumbnail</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <%= render(@documents.order("updated_at DESC")) %>
  </tbody>
</table>

<br>

<%= link_to 'New Document', new_document_path %>

app/views/documents/new.html.erb
<h1>New document</h1>

<%= render 'form' %>

<%= link_to 'Back', project_path(session[:current_project]) %>

app/views/documents/show.html.erb
<table class="table">
	<thead>
    <tr>
      <th>Name</th>
      <th>Scene number</th>
      <th>Location</th>
      <th>Page</th>
    </tr>
  </thead>
  <tbody>
	  <tr><td> <%= @document.name %></td><td><%= @document.scene_number %></td><td><%= @document.location %></td><td><%= @document.page %></td></tr>
  </tbody>
</table>


<p>
<% if @document.pdf? %>
	<div class="embed-container">
	<iframe src="<%= signed_url_for(:original,@document) %>">
	<%= link_to 'View document', signed_url_for(:original,@document) %>
	</iframe>
	</div>
<% elsif false #@document.video? %>

<video id="a240e92d" class="sublime" poster="<%= signed_url_for(:poster, @document) %>" width="400" height="300" title="Midnight Sun" data-uid="a240e92d" preload="none">
 <source src="<%= signed_url_for(:mobile, @document) %>" />
</video>

<% elsif @document.image? %>
	<%= image_tag signed_url_for(:medium,@document) %>
<% elsif false #@document.audio? %>
	<audio controls>
		<source src="<%= signed_url_for(:compressed, @document) %>" type="audio/mp3" />
		<source src="<%= signed_url_for(:ogg_compressed, @document) %>" type="audio/ogg" />
		<%= link_to 'Download document', @document.data.url %>
	</audio>
<% elsif @document.data_host == 'vimeo' %>

<iframe src="https://player.vimeo.com/video/<%= @document.data_ref %>" width="400" height="300" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>

<% elsif @document.data_host == 'youtube' %>

<video class="sublime" data-youtube-id="<%= @document.data_ref %>" width="400" height="300" preload="none">
</video>
<% elsif @document.office? %>
<%= link_to 'Download document', signed_url_for(:original, @document) %> or <%= link_to 'View on Google Docs', google_viewer_url(signed_url_for(:original,@document)),:target => "_blank" %>
<% else %>
	<%= link_to 'Download document', @document.data.url %>
<% end %>
</p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<% if @document.data.to_s !~ /missing\.png/%>
	<%= link_to 'Download original', signed_url_for(:original, @document) %> |
<% end %>
<%= link_to 'Back to project page', project_path(@document.project) %> 

<%= render 'layouts/reminders' %>