config/routes.rb
Cinecinetique::Application.routes.draw do

  resources :paypal_notifications

  resources :budget_lines

  resources :budgets

  resources :proposals

  resources :subscriptions do
    collection do
      get :complete_checkout
      post :payment_notifications
    end
  end

  resources :subscriptions

  devise_for :users, :controllers => { :registrations => 'registrations' }
  
  get '/portfolio', :to => redirect('/portfolio/index.html')

  resources :plans

  controller :scenes do
    post 'sort' => :sort
  end

  controller :static do
    get 'pricing' => :pricing
    get 'terms' => :terms
    get 'product' => :product
  end

  resources :scenes

  resources :projects

  resources :users do
    collection do
      post :invite
    end
  end

  resources :users

  resources :documents do
    get :share
  end

  resources :documents do
    collection do
      get 'heartbeat'
    end
  end

  
  resources :documents

  resources :pdfs, :controller => 'documents'
  resources :mswords, :controller => 'documents'
  resources :msexcels, :controller => 'documents'
  resources :images, :controller => 'documents'
  resources :videos, :controller => 'documents'
  resources :audios, :controller => 'documents'

  resources :workers

    get 'home' => "static#index"
    root :to => "static#index"

end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :documents
	has_many :scenes,  ->  { order "position" }, inverse_of: :project
	has_many :workers, dependent: :destroy
	#before_create :create_bucket
	validates :name, :uniqueness => true
	accepts_nested_attributes_for :workers, :allow_destroy => true

	def bucket_name
		"#{Rails.env}-#{created_by}-#{name.parameterize}"
	end

	def team
		workers.map { |w| w.user}
	end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  authorize_resource

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
    flash[:notice] = "Thank you for your feedback" if params[:from_404] == "want"
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    session[:current_project] = @project.id
  end

  # GET /projects/new
  def new
    @project = Project.new
    @project.workers.build
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.created_by = current_user.id

    project_cycle = ProjectCycle.new(@project)

    respond_to do |format|
      if project_cycle.create
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    session[:current_project] = nil if session[:current_project] == @project.id
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :slug, :date, :preprod_start, :preprod_end, :prod_start,:prod_end, :postprod_start, :postprod_end, :document, :from_404, :workers_attributes => [:id, :role, :department, :user_id])
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
		def vimeo_thumbnail(document)
		vimeo_video_json_url     = "http://vimeo.com/api/v2/video/%s.json" % document.data_ref   # API call

		# Parse the JSON and extract the thumbnail_large url
		thumbnail_image_location = JSON.parse(open(vimeo_video_json_url).read).first['thumbnail_medium'] rescue nil
	end
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <legend>Project details</legend>
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :slug %><br>
      <%= f.text_field :slug %>
    </div>
    <div class="field">
      <%= f.label :date %><br>
      <%= f.date_field :date %>
    </div>
  </fieldset>

    <fieldset>
    <legend>Production details</legend>
    <div class="field">
      <%= f.label :preprod_start %><br>
      <%= f.date_field :preprod_start %>
    </div>
    <div class="field">
      <%= f.label :preprod_end %><br>
      <%= f.date_field :preprod_end %>
    </div>
    <div class="field">
      <%= f.label :prod_start %><br>
      <%= f.date_field :prod_start %>
    </div>
    <div class="field">
      <%= f.label :prod_end %><br>
      <%= f.date_field :prod_end %>
    </div>
    <div class="field">
      <%= f.label :postprod_start %><br>
      <%= f.date_field :postprod_start %>
    </div>
    <div class="field">
      <%= f.label :postprod_end %><br>
      <%= f.date_field :postprod_end %>
    </div>

  </fieldset>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table class="table">
     <tr class="nav-header"><td span="4">Projects you have created</td></tr>
    <% @projects.where("created_by = #{current_user.id}").each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= link_to 'Show', project, :class => "btn btn-mini btn-default" %></td>
        <td><%= link_to 'Edit', edit_project_path(project),  :class => "btn btn-mini btn-primary" %></td>
        <% if can? :destroy, project %>
          <td><%= link_to 'Delete', project, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-mini btn-danger" %></td>
        <% end %>
      </tr>
    <% end %>
    <tr class="nav-header"><td span="4">Projects you participate in</td></tr>
    <% User.find(current_user.id).projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= link_to 'Show', project, :class => "btn btn-mini btn-default" %></td>
        <td><%= link_to 'Edit', edit_project_path(project),  :class => "btn btn-mini btn-primary" %></td>
        <% if can? :destroy, project %>
          <td><%= link_to 'Delete', project, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-mini btn-danger" %></td>
        <% end %>
      </tr>
    <% end %>
</table>

<br>

<% if can? :create, Project %>
  <%= link_to 'New Project', new_project_path %>
<% end %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p>
  <strong>Project Name:</strong>
  <%= @project.name %>
</p>

<%= link_to 'New Document', new_document_path(:project_id => @project.id), :class => "btn btn-primary" %>

<div>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Scene number</th>
      <th>Thumbnail</th>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <%= render(@project.documents.order("updated_at DESC")) %>
  </tbody>
</table>
</div>

<%= link_to 'New Document', new_document_path(:project_id => @project.id), :class => "btn btn-primary" %>
 |
<%= link_to 'Back', projects_path, :class => "btn btn-link" %>