config/routes.rb
Cinecinetique::Application.routes.draw do

  resources :paypal_notifications

  resources :budget_lines

  resources :budgets

  resources :proposals

  resources :subscriptions do
    collection do
      get :complete_checkout
      post :payment_notifications
    end
  end

  resources :subscriptions

  devise_for :users, :controllers => { :registrations => 'registrations' }
  
  get '/portfolio', :to => redirect('/portfolio/index.html')

  resources :plans

  controller :scenes do
    post 'sort' => :sort
  end

  controller :static do
    get 'pricing' => :pricing
    get 'terms' => :terms
    get 'product' => :product
  end

  resources :scenes

  resources :projects

  resources :users do
    collection do
      post :invite
    end
  end

  resources :users

  resources :documents do
    get :share
  end

  resources :documents do
    collection do
      get 'heartbeat'
    end
  end

  
  resources :documents

  resources :pdfs, :controller => 'documents'
  resources :mswords, :controller => 'documents'
  resources :msexcels, :controller => 'documents'
  resources :images, :controller => 'documents'
  resources :videos, :controller => 'documents'
  resources :audios, :controller => 'documents'

  resources :workers

    get 'home' => "static#index"
    root :to => "static#index"

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user
  belongs_to :plan

  STATUSES = {
  		"trial" => -1,
  		"error" => 0,
  		"paid" => 1,
  		"expired" => 2,
  		"terminated" => 3,
  		"cancelled" => 4
  }

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]
  protect_from_forgery :except => [:payment_notifications]

  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @subscriptions = Subscription.all
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def complete_checkout
    # if current_user is subscriber, redirect to dashboard
    if Subscription.where("user_id = #{current_user.id} and start_date < '#{Time.now}'").count > 0
      Rails.logger.debug "completed check out for user_id: #{current_user.id}"
      redirect_to projects_url
    else
    # otherwise render empty page with a message
      render action: 'complete_checkout'
    end
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to @subscription, notice: 'Subscription was successfully created.' }
        format.json { render action: 'show', status: :created, location: @subscription }
      else
        format.html { render action: 'new' }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscriptions/1
  # PATCH/PUT /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to subscriptions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscription_params
      params.require(:subscription).permit(:start_date, :end_date, :amount, :currency, :billing_frequency, :status, :user_id, :plan_id, :initial_amount, :initial_currency, :initial_billing_frequency, :previous_amount, :previous_currency, :previous_billing_frequency, :last_plan_price_change_date)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ipn_params
      params.require(:subscription).permit(:mc_gross, :payer_id, :custom, :item_number, :quantity, :protection_eligibility, :payment_type, :mc_fee, :mc_currency, :payment_status, :payment_gross, :payment_fee, :payment_date, :receiver_email, :receiver_id, :txn_id, :payer_status, :payer_email, :txn_type)
    end

    protected 
    

end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<%= form_for(@subscription) do |f| %>
  <% if @subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
      <% @subscription.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.datetime_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.datetime_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :currency %><br>
    <%= f.text_field :currency %>
  </div>
  <div class="field">
    <%= f.label :billing_frequency %><br>
    <%= f.number_field :billing_frequency %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.number_field :status %>
  </div>
  <div class="field">
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :plan %><br>
    <%= f.text_field :plan %>
  </div>
  <div class="field">
    <%= f.label :initial_amount %><br>
    <%= f.text_field :initial_amount %>
  </div>
  <div class="field">
    <%= f.label :initial_currency %><br>
    <%= f.text_field :initial_currency %>
  </div>
  <div class="field">
    <%= f.label :initial_billing_frequency %><br>
    <%= f.number_field :initial_billing_frequency %>
  </div>
  <div class="field">
    <%= f.label :previous_amount %><br>
    <%= f.text_field :previous_amount %>
  </div>
  <div class="field">
    <%= f.label :previous_currency %><br>
    <%= f.text_field :previous_currency %>
  </div>
  <div class="field">
    <%= f.label :previous_billing_frequency %><br>
    <%= f.number_field :previous_billing_frequency %>
  </div>
  <div class="field">
    <%= f.label :last_plan_price_change_date %><br>
    <%= f.datetime_select :last_plan_price_change_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subscriptions/complete_checkout.html.erb
    <div class="well">
    <p>Thank you for sign up for a plan. Your subscription will be processed shortly.</p>
    <p>Please wait a few minutes before refreshing the page</p>
    </div>

app/views/subscriptions/edit.html.erb
<h1>Editing subscription</h1>

<%= render 'form' %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/index.html.erb
<h1>Listing subscriptions</h1>

<table>
  <thead>
    <tr>
      <th>Start date</th>
      <th>End date</th>
      <th>Amount</th>
      <th>Currency</th>
      <th>Billing frequency</th>
      <th>Status</th>
      <th>User</th>
      <th>Plan</th>
      <th>Initial amount</th>
      <th>Initial currency</th>
      <th>Initial billing frequency</th>
      <th>Previous amount</th>
      <th>Previous currency</th>
      <th>Previous billing frequency</th>
      <th>Last plan price change date</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @subscriptions.each do |subscription| %>
      <tr>
        <td><%= subscription.start_date %></td>
        <td><%= subscription.end_date %></td>
        <td><%= subscription.amount %></td>
        <td><%= subscription.currency %></td>
        <td><%= subscription.billing_frequency %></td>
        <td><%= subscription.status %></td>
        <td><%= subscription.user %></td>
        <td><%= subscription.plan %></td>
        <td><%= subscription.initial_amount %></td>
        <td><%= subscription.initial_currency %></td>
        <td><%= subscription.initial_billing_frequency %></td>
        <td><%= subscription.previous_amount %></td>
        <td><%= subscription.previous_currency %></td>
        <td><%= subscription.previous_billing_frequency %></td>
        <td><%= subscription.last_plan_price_change_date %></td>
        <td><%= link_to 'Show', subscription %></td>
        <td><%= link_to 'Edit', edit_subscription_path(subscription) %></td>
        <td><%= link_to 'Destroy', subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subscription', new_subscription_path %>

app/views/subscriptions/new.html.erb
<h1>New subscription</h1>

<%= render 'form' %>

<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start date:</strong>
  <%= @subscription.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @subscription.end_date %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @subscription.amount %>
</p>

<p>
  <strong>Currency:</strong>
  <%= @subscription.currency %>
</p>

<p>
  <strong>Billing frequency:</strong>
  <%= @subscription.billing_frequency %>
</p>

<p>
  <strong>Status:</strong>
  <%= @subscription.status %>
</p>

<p>
  <strong>User:</strong>
  <%= @subscription.user %>
</p>

<p>
  <strong>Plan:</strong>
  <%= @subscription.plan %>
</p>

<p>
  <strong>Initial amount:</strong>
  <%= @subscription.initial_amount %>
</p>

<p>
  <strong>Initial currency:</strong>
  <%= @subscription.initial_currency %>
</p>

<p>
  <strong>Initial billing frequency:</strong>
  <%= @subscription.initial_billing_frequency %>
</p>

<p>
  <strong>Previous amount:</strong>
  <%= @subscription.previous_amount %>
</p>

<p>
  <strong>Previous currency:</strong>
  <%= @subscription.previous_currency %>
</p>

<p>
  <strong>Previous billing frequency:</strong>
  <%= @subscription.previous_billing_frequency %>
</p>

<p>
  <strong>Last plan price change date:</strong>
  <%= @subscription.last_plan_price_change_date %>
</p>

<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>